//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGDAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerConnection
    {
        public string DatabaseName { get; set; }
        public string ComputerName { get; set; }
        public string CPUID { get; set; }
        public string StructDB { get; set; }
        public string LicenceKey { get; set; }
        public int stt { get; set; }
    }
}
